# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-16 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('socialpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.SocialPost')),
            ],
            bases=('common.socialpost',),
        ),
        migrations.CreateModel(
            name='FacebookSlot',
            fields=[
                ('socialslot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.SocialSlot')),
            ],
            bases=('common.socialslot',),
        ),
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('socialuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.SocialUser')),
                ('facebook_id', models.BigIntegerField(blank=True, null=True)),
                ('picture_url', models.TextField(blank=True, null=True)),
            ],
            bases=('common.socialuser',),
        ),
    ]
