# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-16 10:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_content', models.CharField(max_length=255)),
                ('post_date', models.DateField()),
                ('post_custom_time', models.TimeField(blank=True, null=True)),
                ('is_posted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SocialSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='socialslot',
            name='social_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.SocialUser'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='post_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.SocialSlot'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='social_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.SocialUser'),
        ),
    ]
